### ISSUE TITLE
Debug or Development mode

### ISSUE THREAD

**Issue by salfredogonzalez** [minhng92/odoo-11-docker-compose#1]
The document works perfect for me, just i have a difference between Odoo 10 and Odoo 11, and its that i did can run odoo with dev mode and now, cant find the option, runs as a service, any ideas?

**Comment by minhng92** [comment]
Thanks @salfredogonzalez for your feedback.

By adding "restart: always" field to docker-compose.yml, the containers (Odoo and database) run as services. Note that you have to run compose file in detached mode: `$ docker-compose up -d`.

Please check out the new "docker-compose.yml" file to see the changes.
